---
title: "git_00"
author: "Desiree De La Rosa"
date: "May 25, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Alice was walking beside the White Knight in Looking Glass Land.

"You are sad." the Knight said in an anxious tone: "let me sing you a song to comfort you."

"Is it very long?" Alice asked, for she had heard a good deal of poetry that day.

"It's long." said the Knight, "but it's very, very beautiful. Everybody that hears me sing it -
either it brings tears to their eyes, or else -"

"Or else what?" said Alice, for the Knight had made a sudden pause.

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
      And this was odd, because it was  
      The middle of the night.  
      
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
In the greenest of our valleys  
   By good angels tenanted,  
Once a fair and stately palace-  
   Radiant palace- reared its head.  
In the monarch Thought's dominion-  
   It stood there!  
Never seraph spread a pinion  
   Over fabric half so fair!  
Banners yellow, glorious, golden,  
   On its roof did float and flow,  
(This- all this- was in the olden. 
   Time long ago,). 
And every gentle air that dallied,  
   In that sweet day,  
Along the ramparts plumed and pallid,  
   A winged odor went away.  
